[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# spacetimedb = { git = "https://github.com/clockworklabs/SpacetimeDB", branch = "master", features = ["getrandom"] }
spacetimedb = { version = "0.7.3", features = ["getrandom"]}
log = "0.4"
rand = "0.8.5"
